/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.medidas;
import java.util.List;
import model.Coleta;
import util.MyDefaultTableModel;

/**
 *
 * @author Paulo
 */
public class ViewProjeto_Coleta extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewProjeto_Coleta
     */
    private MyDefaultTableModel tableModel;
    
    public ViewProjeto_Coleta() {
        initComponents();
        
        iniciarTabela();
        util.Internal.retiraBotao(this);
    }
    private void iniciarTabela(){
        tableModel = new MyDefaultTableModel(new String[] {"Medida", "Data", "Autor", "Valor Coleta"}, 0, false);
        jTableColeta.setModel(tableModel);
    }
    private void preencherTabela(List<Coleta> listColeta){
        
        for (int i = 0; i < listColeta.size(); i++) {
            String [] linhas = new String []{};
            tableModel.addRow(linhas);
        }
        jTableColeta.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelBuscarMedida = new javax.swing.JLabel();
        jTextFieldBuscarMedidaColeta = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableColeta = new javax.swing.JTable();
        jButtonExcluirColeta = new javax.swing.JButton();
        jButtonEditarColeta = new javax.swing.JButton();
        jButtonNovaColeta = new javax.swing.JButton();

        setTitle("Coleta");
        setPreferredSize(new java.awt.Dimension(764, 553));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(764, 553));

        jLabelBuscarMedida.setText("Buscar Medida:");

        jTableColeta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableColeta);

        jButtonExcluirColeta.setText("Excluir");

        jButtonEditarColeta.setText("Editar");

        jButtonNovaColeta.setText("Nova");
        jButtonNovaColeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovaColetaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelBuscarMedida)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldBuscarMedidaColeta, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonNovaColeta)
                .addGap(18, 18, 18)
                .addComponent(jButtonEditarColeta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonExcluirColeta)
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBuscarMedida)
                    .addComponent(jTextFieldBuscarMedidaColeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovaColeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEditarColeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonExcluirColeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNovaColetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovaColetaActionPerformed

        ViewProjeto_Coleta_Novo viewProjeto_Coleta_Novo = new ViewProjeto_Coleta_Novo(null, true);
        viewProjeto_Coleta_Novo.setVisible(true);
    }//GEN-LAST:event_jButtonNovaColetaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditarColeta;
    private javax.swing.JButton jButtonExcluirColeta;
    private javax.swing.JButton jButtonNovaColeta;
    private javax.swing.JLabel jLabelBuscarMedida;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableColeta;
    private javax.swing.JTextField jTextFieldBuscarMedidaColeta;
    // End of variables declaration//GEN-END:variables
}
